var ind = []

ind[0]=getABS(1)                        //"Vector Absolute Value"
ind[1]=getACOS(1)                       //"Vector Arccosine"
ind[2]=getAD(1)                         //"Accumulation/Distribution Line"
ind[3]=getADOSC(1,opt1,opt2)            //"Accumulation/Distribution Oscillator"    "option_names":["short period","long period"]
ind[4]=getADX(1,opt1)                   //"Average Directional Movement Index"      "option_names":["period"]
ind[5]=getADXE(1,opt1)                  //"Average Directional Movement Rating"     "option_names":["period"]
ind[6]=getAO(1)                         //"Awesome Oscillator"
ind[7]=getAPO(1,opt1,opt2)              //"Absolute Price Oscillator"               "option_names":["short period","long period"]
ind[8]=getAROON(1,opt1)                 //"Aroon"                                   "option_names":["period"]
ind[9]=getAROONOSC(1,opt1)              //"Aroon Oscillator"                        "option_names":["period"]
ind[10]=getASIN(1)                      //"Vector Arcsine"
ind[11]=getATAN(1)                      //"Vector Arctangent"
ind[12]=getATR(1,opt1)                  //"Average True Range"                      "option_names":["period"]
ind[13]=getAVGPRICE(1)                  //"Average Price"
ind[14]=getBBANDS(1,opt1,opt2)          //"Bollinger Bands"                         "option_names":["period","stddev"]
ind[15]=getBOP(1)                       //"Balance of Power"
ind[16]=getCCI(1,opt1)                  //"Commodity Channel Index"                 "option_names":["period"]
ind[17]=getCEIL(1)                      //"Vector Ceiling"
ind[18]=getCMO(1,opt1)                  //"Chande Momentum Oscillator"              "option_names":["period"]
ind[19]=getCOS(1)                       //"Vector Cosine"
ind[20]=getCOSH(1)                      //"Vector Hyperbolic Cosine"
ind[21]=getCVI(1,opt1)                  //"Chaikins Volatility"                     "option_names":["period"]
ind[22]=getDECAY(1,opt1)                //"Linear Decay"                            "option_names":["period"]
ind[23]=getDEMA(1,opt1)                 //"Double Exponential Moving Average"       "option_names":["period"]
ind[24]=getDI(1,opt1)                   //"Directional Indicator"                   "option_names":["period"]
ind[25]=getDM(1,opt1)                   //"Directional Movement"                    "option_names":["period"]
ind[26]=getDPO(1,opt1)                  //"Detrended Price Oscillator"              "option_names":["period"]
ind[27]=getDX(1,opt1)                   //"Directional Movement Index"              "option_names":["period"]"option_names":["period"]
ind[28]=getEDECAY(1,opt1)               //"Exponential Decay"                       "option_names":["period"]
ind[29]=getEMA(1,opt1)                  //"Exponential Moving Average"              "option_names":["period"]
ind[30]=getEMV(1)                       //"Ease of Movement"   
ind[31]=getEXP(1)                       //"Vector Exponential"
ind[32]=getFISHER(1,opt1)               //"Fisher Transform"                        "option_names":["period"]
ind[33]=getFLOOR(1)                     //"Vector Floor"   
ind[34]=getFOSC(1,opt1)                 //"Forecast Oscillator"                     "option_names":["period"]
ind[35]=getHMA(1,opt1)                  //"Hull Moving Average"                     "option_names":["period"]
ind[36]=getKAMA(1,opt1)                 //"Kaufman Adaptive Moving Average"         "option_names":["period"]
ind[37]=getKVO(1,opt1,opt2)             //"Klinger Volume Oscillator"               "option_names":["short period","long period"]
ind[38]=getLAG(1,opt1)                  //"Lag"                                     "option_names":["period"]
ind[39]=getLINREG(1,opt1)               //"Linear Regression"                       "option_names":["period"]
ind[40]=getLINREGINTERCEPT(1,opt1)      //"Linear Regression Intercept"             "option_names":["period"]
ind[41]=getLINREGSLOPE(1,opt1)          //"Linear Regression Slope"                 "option_names":["period"]
ind[42]=getLN(1)                        //"Vector Natural Log"
ind[43]=getLOG10(1)                     //"Vector Base-10 Log"
ind[44]=getMACD(1,opt1,opt2,opt3)       //"Moving Average Convergence/Divergence"   "option_names":["short period","long period","signal period"]
ind[45]=getMARKETFI(1)                  //"Market Facilitation Index"
ind[46]=getMASS(1,opt1)                 //"Mass Index"                              "option_names":["period"]
ind[47]=getMAX(1,opt1)                  //"Maximum In Period"                       "option_names":["period"]
ind[48]=getMD(1,opt1)                   //"Mean Deviation Over Period"              "option_names":["period"]
ind[49]=getMEDPRICE(1)                  //"Median Price"
ind[50]=getMFI(1,opt1)                  //"Money Flow Index"                        "option_names":["period"]
ind[51]=getMIN(1,opt1)                  //"Minimum In Period"                       "option_names":["period"]
ind[52]=getMOM(1,opt1)                  //"Momentum"                                "option_names":["period"]
ind[53]=getMSW(1,opt1)                  //"Mesa Sine Wave"                          "option_names":["period"]
ind[54]=getNATR(1,opt1)                 //"Normalized Average True Range"           "option_names":["period"]
ind[55]=getNVI(1)                       //"Negative Volume Index"
ind[56]=getOBV(1)                       //"On Balance Volume"
ind[57]=getPPO(1,opt1,opt2)             //"Percentage Price Oscillator"             "option_names":["short period","long period"]
ind[58]=getPSAR(1,opt1,opt2)            //"Parabolic SAR"                           "option_names":["acceleration factor step","acceleration factor maximum"]
ind[59]=getPVI(1)                       //"Positive Volume Index"
ind[60]=getQSTICK(1,opt1)               //"Qstick"                                  "option_names":["period"]
ind[61]=getROC(1,opt1)                  //"Rate of Change"                          "option_names":["period"]
ind[62]=getROCR(1,opt1)                 //"Rate of Change Ratio"                    "option_names":["period"]
ind[63]=getROUND(1)                     //"Vector Round"   
ind[64]=getRSI(1,opt1)                  //"Relative Strength Index"                 "option_names":["period"]
ind[65]=getSIN(1)                       //"Vector Sine"
ind[66]=getSINH(1)                      //"Vector Hyperbolic Sine"
ind[67]=getSMA(1,opt1)                  //"Simple Moving Average"                   "option_names":["period"]
ind[68]=getSQRT(1)                      //"Vector Square Root"
ind[69]=getSTDDEV(1,opt1)               //"Standard Deviation Over Period"          "option_names":["period"]
ind[70]=getSTDERR(1,opt1)               //"Standard Error Over Period"              "option_names":["period"]
ind[71]=getSTOCH(1,opt1,opt2,opt3)      //"Stochastic Oscillator"                   "option_names":["%k period","%k slowing period","%d period"]
ind[72]=getSTOCHRSI(1,opt1)             //"Stochastic RSI"                          "option_names":["period"]
ind[73]=getSUM(1,opt1)                  //"Sum Over Period"                         "option_names":["period"]
ind[74]=getTAN(1)                       //"Vector Tangent"   
ind[75]=getTANH(1)                      //"Vector Hyperbolic Tangent"
ind[76]=getTEMA(1,opt1)                 //"Triple Exponential Moving Average"       "option_names":["period"]
ind[77]=getTODEG(1)                     //"Vector Degree Conversion"   
ind[78]=getTORAD(1)                     //"Vector Radian Conversion
ind[79]=getTR(1)                        //"True Range"
ind[80]=getTRIMA(1,opt1)                //"Triangular Moving Average"               "option_names":["period"]
ind[81]=getTRIX(1,opt1)                 //"Trix"   "option_names":["period"]
ind[82]=getTRUNC(1)                     //"Vector Truncate"
ind[83]=getTSF(1,opt1)                  //"Time Series Forecast"                    "option_names":["period"]
ind[84]=getTYPPRICE(1)                  //"Typical Price"
ind[85]=getULTOSC(1,opt1,opt2,opt3)     //"Ultimate Oscillator"                     "option_names":["short period","medium period","long period"]
ind[86]=getVAR(1,opt1)                  //"Variance Over Period"                    "option_names":["period"]
ind[87]=getVHF(1,opt1)                  //"Vertical Horizontal Filter"              "option_names":["period"]
ind[88]=getVIDYA(1,opt1,opt2,opt3)      //"Variable Index Dynamic Average"          "option_names":["short period","long period","alpha"]
ind[89]=getVOLATILITY(1,opt1)           //"Annualized Historical Volatility"        "option_names":["period"]
ind[90]=getVOSC(1,opt1,opt2)            //"Volume Oscillator"                       "option_names":["short period","long period"]
ind[91]=getVWMA(1,opt1)                 //"Volume Weighted Moving Average"          "option_names":["period"]
ind[92]=getWAD(1)                       //"Williams Accumulation/Distribution"
ind[93]=getWCPRICE(1)                   //"Weighted Close Price"
ind[94]=getWILDERS(1,opt1)              //"Wilders Smoothing"                       "option_names":["period"]
ind[95]=getWILLR(1,opt1)                //"Williams %R"                             "option_names":["period"]
ind[96]=getWMA(1,opt1)                  //"Weighted Moving Average"                 "option_names":["period"]
ind[97]=getZLEMA(1,opt1)                //"Zero-Lag Exponential Moving Average"     "option_names":["period"]
